sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Navdeep1979/docker1 -f Dockerfile.dev .

script:
  - docker run -e CI=true Navdeep1979/docker1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker2"
  env: "Docker2-env"
  bucket_name: "elasticbeanstalk-us-east-1-748746311968"
  bucket_path: "docker2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
